#jinja2: variable_start_string:'${', variable_end_string:'}', trim_blocks: True


---
# Used to obtain all runnning images for cluster vulnerability scans
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-vulnerability-scanner
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-viewer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anchore-cluster-scan-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: cluster-vulnerability-scanner
    namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: pod-viewer
  apiGroup: rbac.authorization.k8s.io
---

# Used to check for sensitive data in kube-system logs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-system-log-scanner
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-system-logs-viewer
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-system-log-scanner-rolebinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kube-system-log-scanner
    namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: kube-system-logs-viewer
  apiGroup: rbac.authorization.k8s.io

